## text_nodes.nim — TextNode composition demo for OpenTUI Nim bindings.
##
## Demonstrates building complex text documents by composing styled text
## segments — analogous to OpenTUI's TextNodeRenderable system.  Cycles
## between two examples:
##   1. Complex Document — a Project Status Report with colored section
##      headers, progress indicators, and styled text
##   2. Dynamic Counter — an animated counter with progress bar that
##      updates in real-time
##
## Original TS source: opentui/packages/examples/src/text-node-demo.ts
##
## Run:  nim c -r -p:src examples/text_nodes.nim
import std/[os, unicode, math, strutils]
import opentui

const
  W = 80'u32
  H = 24'u32
  FramesPerExample = 80   # ~4 seconds at 50ms/frame
  TotalFrames = FramesPerExample * 2
  SleepMs = 50

# ── Color palette (GitHub dark theme from TS source) ───────────

let
  cTitle      = rgb8(0x58, 0xa6, 0xff)   # blue
  cBody       = rgb8(0xc9, 0xd1, 0xd9)   # light gray
  cMuted      = rgb8(0x8b, 0x94, 0x9e)   # gray
  cRed        = rgb8(0xff, 0x7b, 0x72)
  cBlue       = rgb8(0x79, 0xc0, 0xff)
  cGreen      = rgb8(0x56, 0xd3, 0x64)
  cYellow     = rgb8(0xd2, 0x99, 0x22)
  cWhite      = rgb8(0xff, 0xff, 0xff)
  cBg         = rgb8(0x0d, 0x11, 0x17)   # GitHub dark bg
  cPanelBg    = rgb8(0x16, 0x1b, 0x22)   # panel bg
  cBorder     = rgb8(0x50, 0x56, 0x5d)
  cStatusBar  = rgb8(0x58, 0xa6, 0xff)
  cCodeBg     = rgb8(0x0d, 0x11, 0x17)

# ── Drawing helpers ────────────────────────────────────────────

type
  TextSegment = tuple[text: string, fg: OtuiColor16, attrs: uint32]

proc drawStyled(b: Buffer, x, y: int, segments: openArray[TextSegment],
                bg: OtuiColor16) =
  var cx = x
  for seg in segments:
    for r in seg.text.runes:
      b.putCell(cx, y, r, seg.fg, bg, seg.attrs)
      inc cx

proc drawTextAttr(b: Buffer, x, y: int, text: string, fg, bg: OtuiColor16,
                  attrs: uint32 = 0) =
  var cx = x
  for r in text.runes:
    b.putCell(cx, y, r, fg, bg, attrs)
    inc cx

proc fillRect(b: Buffer, x, y, w, h: int, color: OtuiColor16) =
  let bw = int(b.width())
  let bh = int(b.height())
  for cy in max(0, y) ..< min(bh, y + h):
    for cx in max(0, x) ..< min(bw, x + w):
      b.putCell(cx, cy, " ".runeAt(0), color, color)

# ── Example 1: Complex Document ────────────────────────────────

proc drawComplexDocument(b: Buffer, frame: int) =
  let panelX = 2
  let panelY = 1
  let panelW = 76
  let panelH = 22

  b.fillRect(panelX, panelY, panelW, panelH, cPanelBg)
  b.drawBox(panelX, panelY, panelW, panelH, fg = cBorder, bg = cPanelBg)
  b.drawText(panelX + 2, panelY, " TextNode Demo ",
             fg = cBorder, bg = cPanelBg)

  var y = panelY + 2

  # Title
  drawTextAttr(b, panelX + 2, y, "Complex Document Demo",
               cTitle, cPanelBg, uint32(attrBold))
  inc y, 2

  # Intro
  b.drawText(panelX + 2, y, "Building a complete document with TextNodes:",
             cMuted, cPanelBg)
  inc y, 2

  # Section header
  drawStyled(b, panelX + 2, y, [
    ("📋 Project Status Report", cWhite, uint32(attrBold)),
  ], cPanelBg)
  inc y, 2

  # Section 1: Progress
  drawStyled(b, panelX + 2, y, [
    ("✅ ", cGreen, 0'u32),
    ("Progress", cTitle, uint32(attrBold)),
    (": 85% complete", cBody, 0'u32),
  ], cPanelBg)
  inc y

  # Progress bar
  let progBar = repeat("█", 17) & repeat("░", 3)
  drawStyled(b, panelX + 4, y, [
    ("[", cMuted, 0'u32),
    (progBar, cGreen, 0'u32),
    ("]", cMuted, 0'u32),
  ], cPanelBg)
  inc y, 2

  # Section 2: Issues
  drawStyled(b, panelX + 2, y, [
    ("⚠️  ", cYellow, 0'u32),
    ("Issues", cRed, uint32(attrBold)),
    (": 2 minor issues found", cBody, 0'u32),
  ], cPanelBg)
  inc y

  drawStyled(b, panelX + 4, y, [
    ("  • Module A: deprecated API usage", cMuted, 0'u32),
  ], cPanelBg)
  inc y

  drawStyled(b, panelX + 4, y, [
    ("  • Module B: missing error handler", cMuted, 0'u32),
  ], cPanelBg)
  inc y, 2

  # Section 3: Next Steps
  drawStyled(b, panelX + 2, y, [
    ("🚀 ", cGreen, 0'u32),
    ("Next Steps", cTitle, uint32(attrBold)),
    (": Code review and testing", cBody, 0'u32),
  ], cPanelBg)
  inc y

  drawStyled(b, panelX + 4, y, [
    ("  1. ", cBlue, 0'u32),
    ("Run integration test suite", cBody, 0'u32),
  ], cPanelBg)
  inc y

  drawStyled(b, panelX + 4, y, [
    ("  2. ", cBlue, 0'u32),
    ("Update documentation", cBody, 0'u32),
  ], cPanelBg)
  inc y

  drawStyled(b, panelX + 4, y, [
    ("  3. ", cBlue, 0'u32),
    ("Deploy to staging environment", cBody, 0'u32),
  ], cPanelBg)
  inc y, 2

  # Divider
  b.drawText(panelX + 2, y,
    repeat("─", 72), fg = rgb8(0x30, 0x36, 0x3d), bg = cPanelBg)
  inc y

  # Signature
  drawTextAttr(b, panelX + 2, y, "Generated by OpenTUI TextNode Demo",
               cMuted, cPanelBg, uint32(attrItalic))

# ── Example 2: Dynamic Counter ─────────────────────────────────

proc drawDynamicCounter(b: Buffer, frame: int) =
  let panelX = 2
  let panelY = 1
  let panelW = 76
  let panelH = 22

  b.fillRect(panelX, panelY, panelW, panelH, cPanelBg)
  b.drawBox(panelX, panelY, panelW, panelH, fg = cBorder, bg = cPanelBg)
  b.drawText(panelX + 2, panelY, " TextNode Demo ",
             fg = cBorder, bg = cPanelBg)

  var y = panelY + 2

  # Title
  drawTextAttr(b, panelX + 2, y, "Dynamic Updates Demo",
               cTitle, cPanelBg, uint32(attrBold))
  inc y, 2

  b.drawText(panelX + 2, y, "TextNodes can be updated dynamically:",
             cMuted, cPanelBg)
  inc y, 2

  # Animated counter (0-20, cycling)
  let counter = frame mod 21
  let maxCount = 20

  # Counter
  drawStyled(b, panelX + 2, y, [
    ("Counter: ", cGreen, uint32(attrBold)),
    ($counter, cWhite, 0'u32),
  ], cPanelBg)
  inc y, 2

  # Status based on counter
  let status = if counter < 5: "Starting"
               elif counter < 15: "Running"
               else: "Finishing"
  let statusColor = if counter < 5: cBlue
                    elif counter < 15: cGreen
                    else: cYellow
  drawStyled(b, panelX + 2, y, [
    ("Status: ", cBlue, 0'u32),
    (status, statusColor, uint32(attrBold)),
  ], cPanelBg)
  inc y, 2

  # Progress bar
  let progress = int(float(counter) / float(maxCount) * 20.0)
  let progBar = repeat("█", progress) & repeat("░", 20 - progress)
  drawStyled(b, panelX + 2, y, [
    ("Progress: [", cYellow, 0'u32),
    (progBar, cGreen, 0'u32),
    ("]", cYellow, 0'u32),
  ], cPanelBg)
  inc y, 2

  # Percentage
  let pct = int(float(counter) / float(maxCount) * 100.0)
  drawStyled(b, panelX + 2, y, [
    ($pct & "% complete", cBody, 0'u32),
  ], cPanelBg)
  inc y, 3

  # Animated wave
  let waveY = sin(float(frame) * 0.2) * 5
  drawStyled(b, panelX + 2, y, [
    ("Wave: ", cTitle, 0'u32),
    ((if waveY >= 0: "+" else: ""), cGreen, 0'u32),
    (formatFloat(waveY, ffDecimal, 2),
     (if waveY >= 0: cGreen else: cRed), 0'u32),
  ], cPanelBg)
  inc y, 2

  # CPU-like meter
  let cpuVal = sin(float(frame) * 0.1) * 50 + 50
  let cpuBarLen = int(cpuVal / 5.0)
  let cpuBar = repeat("█", cpuBarLen) & repeat("░", 20 - cpuBarLen)
  drawStyled(b, panelX + 2, y, [
    ("CPU:    [", cRed, 0'u32),
    (cpuBar, if cpuVal > 80: cRed else: cGreen, 0'u32),
    ("] ", cRed, 0'u32),
    (formatFloat(cpuVal, ffDecimal, 1) & "%", cWhite, 0'u32),
  ], cPanelBg)
  inc y, 2

  # Memory-like meter
  let memVal = cos(float(frame) * 0.15) * 30 + 60
  let memBarLen = int(memVal / 5.0)
  let memBar = repeat("█", memBarLen) & repeat("░", 20 - memBarLen)
  drawStyled(b, panelX + 2, y, [
    ("Memory: [", rgb8(0xFF, 0x6B, 0x6B), 0'u32),
    (memBar, if memVal > 85: cRed else: cYellow, 0'u32),
    ("] ", rgb8(0xFF, 0x6B, 0x6B), 0'u32),
    (formatFloat(memVal, ffDecimal, 1) & "%", cWhite, 0'u32),
  ], cPanelBg)
  inc y, 3

  # Instructions
  drawStyled(b, panelX + 2, y, [
    ("Press 1-4 to see different examples (demo auto-cycles)",
     cMuted, uint32(attrItalic)),
  ], cPanelBg)

# ── Main ───────────────────────────────────────────────────────

proc main() =
  var r = newRenderer(W, H)
  setupTerminal()
  try:
    for frame in 0 .. TotalFrames:
      var b = r.nextBuffer()
      b.clear(cBg)

      if frame < FramesPerExample:
        b.drawComplexDocument(frame)
      else:
        b.drawDynamicCounter(frame - FramesPerExample)

      discard r.render(true)
      sleep(SleepMs)
  finally:
    restoreTerminal()

main()
